<script setup>
// Generated by GitHub Copilot
import { ref, onMounted, computed } from "vue";
import { api } from "../api/";
import CreateChoreForm from "../components/CreateChoreForm.vue";
import CreateHouseForm from "../components/CreateHouseForm.vue";
import JoinHouseForm from "../components/JoinHouseForm.vue";
import InviteCodeGenerator from "../components/InviteCodeGenerator.vue";
import { RouterLink } from "vue-router";

// State
const user = ref(null);
const house = ref(null);
const houseUsers = ref([]);
const houseChores = ref([]);
const userChores = ref([]);
const showCreateJoin = ref(false);
const showCreateHouseForm = ref(false);
const showJoinHouseForm = ref(false);
const loading = ref(true);
const error = ref(null);
const showCreateChoreModal = ref(false);
const showInviteCodeModal = ref(false);

// Pagination state
const choresPagination = ref({
  nextCursor: null,
  hasNextPage: false,
  totalCount: 0,
  limit: 10,
  loading: false,
});

const userChoresPagination = ref({
  nextCursor: null,
  hasNextPage: false,
  totalCount: 0,
  limit: 10,
  loading: false,
});

// Computed properties
const isHouseOwner = computed(() => {
  return user.value?.id === house.value?.createdById;
});

const totalChores = computed(() => {
  return choresPagination.value.totalCount || houseChores.value.length;
});

const completedChores = computed(() => {
  // For completed/pending ratio, we can only use the data we've loaded so far
  const loadedCompletedCount = houseChores.value.filter(
    (chore) => chore.isCompleted
  ).length;
  // If all chores are loaded, this is accurate; otherwise, it's just what we've loaded
  return loadedCompletedCount;
});

const pendingChores = computed(() => {
  // For loaded chores, we know exactly which ones are pending
  const loadedPendingCount = houseChores.value.filter(
    (chore) => !chore.isCompleted
  ).length;

  // Use the totalCount from pagination to calculate a more accurate pending count
  // If we know the total and completed, we can infer pending
  if (choresPagination.value.totalCount) {
    return choresPagination.value.totalCount - completedChores.value;
  }

  return loadedPendingCount;
});

const sortedUsers = computed(() => {
  return [...houseUsers.value].sort(
    (a, b) => (b.points || 0) - (a.points || 0)
  );
});

// Fetch user and their houses
async function loadDashboard() {
  loading.value = true;
  error.value = null;

  try {
    const { data: me } = await api.get("/auth/me");
    user.value = me;

    try {
      if (me.houseId === null) {
        showCreateJoin.value = true;
        house.value = null;
      } else {
        const { data: houseData } = await api.get(`/houses/${me.houseId}`);
        house.value = houseData;
        showCreateJoin.value = false;

        try {
          const { data: users } = await api.get(
            `/houses/${house.value.id}/users`
          );

          // Clear previous data
          houseChores.value = [];
          userChores.value = [];

          // Reset pagination state but preserve totalCount if already loaded
          const prevTotalCount = choresPagination.value.totalCount;
          choresPagination.value = {
            nextCursor: null,
            hasNextPage: false,
            totalCount: prevTotalCount, // Keep the total count initially so UI doesn't flicker
            limit: 10,
            loading: false,
          };

          const prevUserTotalCount = userChoresPagination.value.totalCount;
          userChoresPagination.value = {
            nextCursor: null,
            hasNextPage: false,
            totalCount: prevUserTotalCount, // Keep the total count initially
            limit: 10,
            loading: false,
          };

          houseUsers.value = users?.data || [];

          // Load initial chores with pagination
          await loadHouseChores();
          await loadUserChores(me.id);
        } catch (err) {
          console.error("Error fetching house details:", err);
          error.value = "Failed to load house details";
        }
      }
    } catch (err) {
      console.error("Error fetching user house:", err);
      error.value = "Failed to load your house";
      showCreateJoin.value = true;
    }
  } catch (err) {
    console.error("Error fetching user data:", err);
    error.value = "Failed to load user information";
  } finally {
    loading.value = false;
  }
}

// Load house chores with pagination
async function loadHouseChores() {
  if (!house.value || choresPagination.value.loading) return;

  choresPagination.value.loading = true;

  try {
    const cursor = choresPagination.value.nextCursor;
    const limit = choresPagination.value.limit;

    let url = `/houses/${house.value.id}/chores?limit=${limit}`;
    if (cursor) {
      url += `&cursor=${cursor}`;
    }

    const { data: response } = await api.get(url);

    // If this is the first load or a refresh, replace the array
    // Otherwise append to existing array for "load more" functionality
    if (!cursor) {
      houseChores.value = response?.data || [];
    } else {
      houseChores.value = [...houseChores.value, ...(response?.data || [])];
    }

    // Always update the total count immediately to ensure UI displays correct numbers
    if (response?.pagination?.totalCount) {
      choresPagination.value.totalCount = response.pagination.totalCount;
    }

    // Update pagination state
    choresPagination.value = {
      ...choresPagination.value,
      nextCursor: response?.pagination?.nextCursor || null,
      hasNextPage: response?.pagination?.hasNextPage || false,
      totalCount:
        response?.pagination?.totalCount ||
        choresPagination.value.totalCount ||
        0,
    };
  } catch (err) {
    console.error("Error loading house chores:", err);
  } finally {
    choresPagination.value.loading = false;
  }
}

// Load user chores with pagination
async function loadUserChores(userId) {
  if (!house.value || userChoresPagination.value.loading) return;

  userChoresPagination.value.loading = true;

  try {
    const cursor = userChoresPagination.value.nextCursor;
    const limit = userChoresPagination.value.limit;

    let url = `/houses/${house.value.id}/chores?assignedTo=${userId}&limit=${limit}`;
    if (cursor) {
      url += `&cursor=${cursor}`;
    }

    const { data: response } = await api.get(url);

    // If this is the first load or a refresh, replace the array
    // Otherwise append to existing array for "load more" functionality
    if (!cursor) {
      userChores.value = response?.data || [];
    } else {
      userChores.value = [...userChores.value, ...(response?.data || [])];
    }

    // Always update the total count immediately to ensure UI displays correct numbers
    if (response?.pagination?.totalCount) {
      userChoresPagination.value.totalCount = response.pagination.totalCount;
    }

    // Update pagination state
    userChoresPagination.value = {
      ...userChoresPagination.value,
      nextCursor: response?.pagination?.nextCursor || null,
      hasNextPage: response?.pagination?.hasNextPage || false,
      totalCount:
        response?.pagination?.totalCount ||
        userChoresPagination.value.totalCount ||
        0,
    };
  } catch (err) {
    console.error("Error loading user chores:", err);
  } finally {
    userChoresPagination.value.loading = false;
  }
}

onMounted(() => {
  loadDashboard();
});

// Handlers for showing forms
function openCreateHouse() {
  showCreateHouseForm.value = true;
  showJoinHouseForm.value = false;
}

function openJoinHouse() {
  showJoinHouseForm.value = true;
  showCreateHouseForm.value = false;
}

function openCreateChoreModal() {
  showCreateChoreModal.value = true;
}

function closeCreateChoreModal() {
  showCreateChoreModal.value = false;
}

function openInviteCodeModal() {
  showInviteCodeModal.value = true;
}

function closeInviteCodeModal() {
  showInviteCodeModal.value = false;
}

function deleteHouse() {
  if (
    confirm(
      "Are you sure you want to delete this house? This action cannot be undone."
    )
  ) {
    api
      .delete(`/houses/${house.value.id}`)
      .then(() => {
        loadDashboard();
      })
      .catch((error) => {
        console.error("Error deleting house:", error);
      });
  }
}

function leaveHouse() {
  if (
    confirm(
      "Are you sure you want to leave this house? You'll need a new invitation to rejoin."
    )
  ) {
    api
      .delete(`/houses/${house.value.id}/leave`)
      .then(() => {
        loadDashboard();
      })
      .catch((error) => {
        console.error("Error leaving house:", error);
      });
  }
}

// Mark chore as complete and update user points
function markChoreComplete(choreId) {
  // Find the chore first to get its details
  const chore = houseChores.value.find((c) => c.id === choreId);
  if (!chore) return;

  api
    .patch(`/chores/${choreId}`, { completed: true })
    .then((response) => {
      const updatedChore = response.data;

      // Update local chore state
      const choreIndex = houseChores.value.findIndex((c) => c.id === choreId);
      if (choreIndex !== -1) {
        houseChores.value[choreIndex].isCompleted = true;
      }

      const userChoreIndex = userChores.value.findIndex(
        (c) => c.id === choreId
      );
      if (userChoreIndex !== -1) {
        userChores.value[userChoreIndex].isCompleted = true;
      }

      // Update points in the UI for the assigned user
      if (chore.assignedToId) {
        const userIndex = houseUsers.value.findIndex(
          (u) => u.id === chore.assignedToId
        );
        if (userIndex !== -1) {
          // Increment the user's points
          houseUsers.value[userIndex].points =
            (houseUsers.value[userIndex].points || 0) + (chore.points || 0);
        }
      }
    })
    .catch((error) => {
      console.error("Error marking chore as complete:", error);
    });
}

function formatDate(dateString) {
  if (!dateString) return "";
  const date = new Date(dateString);
  return date.toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}
</script>

<template>
  <div class="dashboard-container">
    <!-- Loading state -->
    <div v-if="loading" class="loading-container">
      <div class="loader"></div>
      <p class="loading-text">Loading your dashboard...</p>
    </div>

    <!-- Error state -->
    <div v-else-if="error" class="alert alert-error">
      <div class="alert-content">
        <p class="alert-title">{{ error }}</p>
        <button @click="loadDashboard" class="btn btn-sm">Retry</button>
      </div>
    </div>

    <!-- Create/Join House state -->
    <div v-else-if="showCreateJoin" class="container">
      <div class="card welcome-card">
        <div class="card-body text-center">
          <!-- Generated by GitHub Copilot -->
          <h2 class="welcome-title">Welcome to ChoreSprint!</h2>
          <p class="welcome-subtitle">
            You're not part of any house yet. Create your own or join an
            existing one.
          </p>

          <div class="action-buttons">
            <button @click="openCreateHouse" class="btn btn-primary">
              Create House
            </button>
            <button @click="openJoinHouse" class="btn btn-outline">
              Join House
            </button>
          </div>

          <div class="form-container">
            <CreateHouseForm
              v-if="showCreateHouseForm"
              @created="loadDashboard"
              class="house-form"
            />
            <JoinHouseForm
              v-if="showJoinHouseForm"
              @joined="loadDashboard"
              class="house-form"
            />
          </div>
        </div>
      </div>
    </div>

    <!-- Dashboard with house -->
    <div v-else class="container">
      <div class="dashboard-header">
        <!-- Generated by GitHub Copilot -->
        <h1 class="dashboard-title">Dashboard</h1>
        <p class="dashboard-subtitle">Manage your house and chores</p>
      </div>

      <div class="dashboard-grid">
        <!-- House information -->
        <div class="card house-info-card">
          <div class="card-header">
            <h2 class="card-title">House Information</h2>
          </div>

          <div class="card-body">
            <div class="house-details">
              <h3 class="house-name">{{ house?.name }}</h3>

              <div class="house-stats">
                <div class="stat-box">
                  <div class="stat-value">{{ houseUsers.length }}</div>
                  <div class="stat-label">Members</div>
                </div>

                <div class="stat-box">
                  <div class="stat-value">{{ totalChores }}</div>
                  <div class="stat-label">Total Chores</div>
                </div>

                <div class="stat-box">
                  <div class="stat-value">{{ completedChores }}</div>
                  <div class="stat-label">Completed</div>
                </div>

                <div class="stat-box">
                  <div class="stat-value">{{ pendingChores }}</div>
                  <div class="stat-label">Pending</div>
                </div>
              </div>
            </div>

            <div class="house-actions">
              <button
                v-if="isHouseOwner"
                @click="openInviteCodeModal"
                class="btn btn-primary btn-sm"
              >
                <span class="btn-icon">📩</span> Invite Members
              </button>

              <button
                v-if="isHouseOwner"
                @click="deleteHouse"
                class="btn btn-error btn-sm"
              >
                <span class="btn-icon">🗑️</span> Delete House
              </button>

              <button v-else @click="leaveHouse" class="btn btn-outline btn-sm">
                <span class="btn-icon">👋</span> Leave House
              </button>
            </div>
          </div>
        </div>

        <!-- Leaderboard -->
        <div class="card leaderboard-card">
          <div class="card-header">
            <h2 class="card-title">Leaderboard</h2>
          </div>

          <div class="card-body">
            <div v-if="sortedUsers.length === 0" class="empty-state">
              <p>No users in this house yet.</p>
            </div>

            <ul v-else class="leaderboard-list">
              <!-- Generated by GitHub Copilot -->
              <li
                v-for="(houseUser, index) in sortedUsers"
                :key="houseUser.id"
                class="leaderboard-item"
                :class="{ 'current-user': houseUser.id === user.id }"
              >
                <div class="rank">{{ index + 1 }}</div>
                <div class="user-avatar">
                  <img
                    :src="
                      houseUser.avatarUrl ||
                      `https://ui-avatars.com/api/?name=${encodeURIComponent(houseUser.name)}`
                    "
                    :alt="houseUser.name"
                    class="avatar"
                  />
                </div>
                <div class="user-info">
                  <div class="user-name">{{ houseUser.name }}</div>
                  <div v-if="index === 0" class="user-badge">
                    👑 House Leader
                  </div>
                </div>
                <div class="user-points">{{ houseUser.points || 0 }} pts</div>
              </li>
            </ul>
          </div>
        </div>

        <!-- All house chores -->
        <div class="card chores-card">
          <div class="card-header">
            <h2 class="card-title">House Chores</h2>
            <button
              v-if="isHouseOwner"
              @click="openCreateChoreModal"
              class="btn btn-primary btn-sm"
            >
              <span class="btn-icon">+</span> Add Chore
            </button>
          </div>

          <div class="card-body">
            <div
              v-if="houseChores.length === 0 && !choresPagination.loading"
              class="empty-state"
            >
              <!-- Generated by GitHub Copilot -->
              <p>No chores have been created yet.</p>
              <button
                v-if="isHouseOwner"
                @click="openCreateChoreModal"
                class="btn btn-primary btn-sm"
              >
                Create your first chore
              </button>
            </div>

            <div
              v-else-if="choresPagination.loading && !houseChores.length"
              class="loading-container"
            >
              <div class="loader"></div>
              <p>Loading chores...</p>
            </div>

            <div v-else class="chore-list">
              <div
                v-for="chore in houseChores"
                :key="chore.id"
                class="chore-card"
                :class="{ completed: chore.isCompleted }"
              >
                <div
                  class="chore-status"
                  :class="{ completed: chore.isCompleted }"
                >
                  <span class="status-icon">✓</span>
                </div>

                <div class="chore-content">
                  <h3 class="chore-title">{{ chore.title }}</h3>
                  <p v-if="chore.description" class="chore-description">
                    {{ chore.description }}
                  </p>

                  <div class="chore-meta">
                    <span v-if="chore.dueDate" class="chore-due"
                      >Due: {{ formatDate(chore.dueDate) }}</span
                    >
                    <span v-if="chore.points" class="chore-points"
                      >{{ chore.points }} pts</span
                    >
                    <span v-if="chore.assignedToId" class="chore-assigned">
                      Assigned to:
                      {{
                        chore.assignedTo?.name ||
                        houseUsers.find((u) => u.id === chore.assignedToId)
                          ?.name ||
                        "Unknown"
                      }}
                    </span>
                  </div>
                </div>

                <div class="chore-actions">
                  <template v-if="!chore.isCompleted">
                    <button
                      v-if="
                        chore.assignedToId === user.id || !chore.assignedToId
                      "
                      @click="markChoreComplete(chore.id)"
                      class="btn btn-sm btn-success"
                    >
                      Complete
                    </button>
                  </template>
                  <span v-else class="completed-badge">Completed</span>

                  <RouterLink
                    v-if="isHouseOwner"
                    :to="`/chores/${chore.id}/edit`"
                    class="btn btn-sm btn-outline"
                  >
                    Edit
                  </RouterLink>
                </div>
              </div>

              <!-- Pagination controls -->
              <div
                v-if="choresPagination.hasNextPage"
                class="pagination-controls"
              >
                <button
                  @click="loadHouseChores"
                  class="btn btn-primary btn-sm load-more-btn"
                  :disabled="choresPagination.loading"
                >
                  <span
                    v-if="choresPagination.loading"
                    class="loader-inline"
                  ></span>
                  <span v-else>Load More Chores</span>
                </button>
              </div>
            </div>
          </div>
        </div>

        <!-- Your chores -->
        <div class="card your-chores-card">
          <div class="card-header">
            <h2 class="card-title">Your Chores</h2>
          </div>

          <div class="card-body">
            <div
              v-if="userChores.length === 0 && !userChoresPagination.loading"
              class="empty-state"
            >
              <!-- Generated by GitHub Copilot -->
              <p>You don't have any chores assigned.</p>
            </div>

            <div
              v-else-if="userChoresPagination.loading && !userChores.length"
              class="loading-container"
            >
              <div class="loader"></div>
              <p>Loading your chores...</p>
            </div>

            <div v-else class="chore-list">
              <div
                v-for="chore in userChores"
                :key="chore.id"
                class="chore-card"
                :class="{ completed: chore.isCompleted }"
              >
                <div
                  class="chore-status"
                  :class="{ completed: chore.isCompleted }"
                >
                  <span class="status-icon">✓</span>
                </div>

                <div class="chore-content">
                  <h3 class="chore-title">{{ chore.title }}</h3>
                  <p v-if="chore.description" class="chore-description">
                    {{ chore.description }}
                  </p>

                  <div class="chore-meta">
                    <span v-if="chore.dueDate" class="chore-due"
                      >Due: {{ formatDate(chore.dueDate) }}</span
                    >
                    <span v-if="chore.points" class="chore-points"
                      >{{ chore.points }} pts</span
                    >
                  </div>
                </div>

                <div class="chore-actions">
                  <button
                    v-if="!chore.isCompleted"
                    @click="markChoreComplete(chore.id)"
                    class="btn btn-sm btn-success"
                  >
                    Complete
                  </button>
                  <span v-else class="completed-badge">Completed</span>
                </div>
              </div>

              <!-- Pagination controls -->
              <div
                v-if="userChoresPagination.hasNextPage"
                class="pagination-controls"
              >
                <button
                  @click="loadUserChores(user.id)"
                  class="btn btn-primary btn-sm load-more-btn"
                  :disabled="userChoresPagination.loading"
                >
                  <span
                    v-if="userChoresPagination.loading"
                    class="loader-inline"
                  ></span>
                  <span v-else>Load More Chores</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Create Chore Modal -->
    <div v-if="showCreateChoreModal" class="modal">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title">Add New Chore</h2>
          <button @click="closeCreateChoreModal" class="close-button">
            &times;
          </button>
        </div>

        <div class="modal-body">
          <CreateChoreForm
            :house-id="house?.id"
            @created="
              () => {
                loadDashboard();
                closeCreateChoreModal();
              }
            "
          />
        </div>
      </div>
    </div>

    <!-- Invite Code Modal -->
    <div v-if="showInviteCodeModal" class="modal">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title">Invite Members</h2>
          <button @click="closeInviteCodeModal" class="close-button">
            &times;
          </button>
        </div>

        <div class="modal-body">
          <InviteCodeGenerator :house-id="house?.id" />
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* Generated by GitHub Copilot */
.dashboard-container {
  min-height: calc(100vh - 180px); /* Adjust for header and footer */
}

.loading-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  min-height: 200px;
}

.loading-text {
  margin-top: var(--spacing-md);
  color: var(--gray);
}

.dashboard-header {
  margin-bottom: var(--spacing-xl);
}

.dashboard-title {
  margin-bottom: var(--spacing-xs);
}

.dashboard-subtitle {
  color: var(--gray);
}

.dashboard-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: var(--spacing-lg);
}

/* Card layouts */
.house-info-card {
  grid-column: span 2;
}

.chores-card {
  grid-column: span 2;
}

/* House info styles */
.house-details {
  margin-bottom: var(--spacing-lg);
}

.house-name {
  font-size: var(--font-size-2xl);
  color: var(--primary);
  margin-bottom: var(--spacing-md);
}

.house-stats {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-md);
  margin-top: var(--spacing-lg);
}

.stat-box {
  flex: 1;
  min-width: 100px;
  background-color: var(--light);
  padding: var(--spacing-md);
  border-radius: var(--radius-md);
  text-align: center;
}

.stat-value {
  font-size: var(--font-size-2xl);
  font-weight: bold;
  color: var(--primary);
}

.stat-label {
  color: var(--gray);
  font-size: var(--font-size-sm);
}

.house-actions {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-md);
  margin-top: var(--spacing-lg);
}

/* Leaderboard styles */
.leaderboard-list {
  list-style: none;
  padding: 0;
}

.leaderboard-item {
  display: flex;
  align-items: center;
  padding: var(--spacing-sm);
  margin-bottom: var(--spacing-sm);
  border-radius: var(--radius-md);
  background-color: var(--light);
  transition: transform var(--transition-fast);
}

.leaderboard-item:hover {
  transform: translateX(5px);
}

.leaderboard-item.current-user {
  background-color: rgba(67, 97, 238, 0.1);
}

.rank {
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--primary);
  color: var(--white);
  border-radius: 50%;
  font-weight: bold;
  margin-right: var(--spacing-md);
}

.user-avatar {
  margin-right: var(--spacing-md);
}

.user-info {
  flex: 1;
}

.user-name {
  font-weight: 500;
}

.user-badge {
  font-size: var(--font-size-xs);
  color: var(--secondary);
}

.user-points {
  font-weight: bold;
  color: var(--primary-dark);
}

/* Chore styles */
.chore-list {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-md);
}

.chore-card {
  display: flex;
  align-items: center;
  padding: var(--spacing-md);
  background-color: var(--white);
  border-radius: var(--radius-md);
  border-left: 4px solid var(--gray-light);
  box-shadow: var(--shadow-sm);
  transition: all var(--transition-fast);
}

.chore-card:hover {
  transform: translateY(-2px);
  box-shadow: var(--shadow-md);
}

.chore-card.completed {
  border-left-color: var(--success);
  background-color: rgba(16, 185, 129, 0.05);
}

.chore-status {
  width: 24px;
  height: 24px;
  border-radius: 50%;
  border: 2px solid var(--gray-light);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: var(--spacing-md);
}

.chore-status.completed {
  background-color: var(--success);
  border-color: var(--success);
}

.status-icon {
  display: none;
  color: var(--white);
  font-size: var(--font-size-sm);
}

.chore-status.completed .status-icon {
  display: inline;
}

.chore-content {
  flex: 1;
}

.chore-title {
  font-size: var(--font-size-lg);
  margin-bottom: var(--spacing-xs);
}

.chore-description {
  color: var(--gray);
  margin-bottom: var(--spacing-xs);
}

.chore-meta {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-md);
  margin-top: var(--spacing-xs);
  font-size: var(--font-size-sm);
}

.chore-due {
  color: var(--gray-dark);
}

.chore-points {
  color: var(--primary);
  font-weight: 500;
}

.chore-assigned {
  color: var(--gray);
}

.chore-actions {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-sm);
  margin-left: var(--spacing-md);
}

.completed-badge {
  display: inline-block;
  padding: var(--spacing-xs) var(--spacing-sm);
  background-color: var(--success);
  color: var(--white);
  border-radius: var(--radius-full);
  font-size: var(--font-size-xs);
  font-weight: 500;
}

/* Pagination styles */
.pagination-controls {
  display: flex;
  justify-content: center;
  margin-top: var(--spacing-lg);
}

.load-more-btn {
  min-width: 150px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.loader-inline {
  display: inline-block;
  width: 16px;
  height: 16px;
  border: 2px solid rgba(255, 255, 255, 0.3);
  border-radius: 50%;
  border-top-color: var(--white);
  animation: spin 1s ease-in-out infinite;
  margin-right: var(--spacing-xs);
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

/* Form styles */
.welcome-card {
  max-width: 600px;
  margin: 0 auto;
}

.welcome-title {
  font-size: var(--font-size-3xl);
  margin-bottom: var(--spacing-md);
  color: var(--primary);
}

.welcome-subtitle {
  color: var(--gray);
  margin-bottom: var(--spacing-xl);
}

.action-buttons {
  display: flex;
  justify-content: center;
  gap: var(--spacing-md);
  margin-bottom: var(--spacing-lg);
}

.form-container {
  max-width: 400px;
  margin: 0 auto;
}

.house-form {
  animation: fadeIn var(--transition-normal);
}

/* Modal styles */
.modal {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background-color: var(--white);
  border-radius: var(--radius-lg);
  width: 90%;
  max-width: 500px;
  max-height: 90vh;
  overflow-y: auto;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: var(--spacing-lg);
  border-bottom: 1px solid var(--light);
}

.modal-title {
  font-size: var(--font-size-xl);
  color: var(--dark);
  margin: 0;
}

.close-button {
  background: none;
  border: none;
  font-size: 1.5rem;
  line-height: 1;
  cursor: pointer;
  color: var(--gray);
}

.modal-body {
  padding: var(--spacing-lg);
}

/* Button specific styles */
.btn-error {
  background-color: var(--error);
  color: var(--white);
}

.btn-error:hover {
  background-color: #e03131;
}

.btn-success {
  background-color: var(--success);
  color: var(--white);
}

.btn-success:hover {
  background-color: #0ca678;
}

/* Responsive styles */
@media (max-width: 768px) {
  .dashboard-grid {
    grid-template-columns: 1fr;
  }

  .house-info-card,
  .chores-card {
    grid-column: span 1;
  }

  .house-stats {
    flex-wrap: wrap;
  }

  .stat-box {
    min-width: 80px;
  }

  .action-buttons {
    flex-direction: column;
  }
}
</style>
