<template>
  <div class="manage-sub container">
    <h2>Subscription</h2>
    <div v-if="loading" class="loader"></div>
    <p v-else-if="error" class="error">{{ error }}</p>
    <div v-else>
      <div v-if="subscription && subscription.status === 'active'">
        <button class="btn btn-primary" @click="cancel" :disabled="cancelLoading">
          Cancel Subscription
        </button>
      </div>
      <div v-else>
        <p>You do not have an active subscription.</p>
        <RouterLink to="/subscribe" class="btn btn-primary">Buy Subscription</RouterLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// Generated by GitHub Copilot
import { ref, onMounted } from 'vue'
import { api } from '../api'
import { RouterLink } from 'vue-router'

interface SubscriptionInfo {
  id: string
  status: string
}

const loading = ref(true)
const cancelLoading = ref(false)
const error = ref('')
const subscription = ref<SubscriptionInfo | null>(null)

async function fetchSub() {
  loading.value = true
  error.value = ''
  try {
    const res = await api.get('/payments/subscription')
    subscription.value = res.data.subscribed === false ? null : res.data
  } catch (e) {
    error.value = 'Failed to load subscription.'
  } finally {
    loading.value = false
  }
}

async function cancel() {
  if (!subscription.value) return
  cancelLoading.value = true
  error.value = ''
  try {
    await api.post('/payments/subscription/cancel')
    await fetchSub()
  } catch (e) {
    error.value = 'Failed to cancel subscription.'
  } finally {
    cancelLoading.value = false
  }
}

onMounted(fetchSub)
</script>

<style scoped>
.manage-sub {
  padding: 2rem;
  text-align: center;
}
.error {
  color: red;
}
</style>