<script setup lang="ts">
// Generated by GitHub Copilot
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { api } from "./api";
import { getGoogleAuthUrl } from "./utils/config";
import { getAuthStatus } from "./lib/auth";

interface User {
  id: string;
  name: string;
  email: string;
  avatarUrl?: string;
}

// State
const user = ref<User | null>(null);
const isLoading = ref(true);
const dropdownOpen = ref(false);
const subscriptionRequired = ref(false);

// Get router
const router = useRouter();

// Toggle dropdown menu
const toggleDropdown = () => {
  dropdownOpen.value = !dropdownOpen.value;
};

// Close dropdown when clicking outside
const closeDropdownOnClickOutside = (event: MouseEvent) => {
  const userMenu = document.querySelector(".user-menu");
  if (
    userMenu &&
    !userMenu.contains(event.target as Node) &&
    dropdownOpen.value
  ) {
    dropdownOpen.value = false;
  }
};

// Add event listener to close dropdown on clicks outside the menu
onMounted(() => {
  document.addEventListener("click", closeDropdownOnClickOutside);
});

// Check if user is logged in
const checkAuth = async () => {
  try {
    const status = await getAuthStatus();
    if (status.authed && !status.subscriptionRequired) {
      user.value = status.user;
    } else if (status.subscriptionRequired) {
      user.value = status.user;
      subscriptionRequired.value = true;
      router.push("/subscribe");
    } else {
      user.value = null;
    }
  } catch (error) {
    console.error("Authentication check failed:", error);
    user.value = null;
  } finally {
    isLoading.value = false;
  }
};

// Handle logout
const logout = async () => {
  try {
    await api.post("/auth/logout");
    user.value = null;
    // Redirect to home page and refresh the page to clear any cached data
    router.push("/").then(() => {
      window.location.reload();
    });
  } catch (error) {
    console.error("Logout failed:", error);
  }
};

// Check auth status on component mount
onMounted(() => {
  checkAuth();
});
</script>

<template>
  <div class="app-container">
    <!-- Navigation bar -->
    <header class="navbar">
      <div class="container nav-container">
        <div class="nav-brand">
          <router-link to="/" class="nav-brand-link">
            <!-- Generated by GitHub Copilot -->
            <span class="brand-icon">🏃</span> ChoreSprint
          </router-link>
        </div>

        <nav class="nav-links" v-if="!isLoading">
          <div class="nav-links-container">
            <router-link to="/" class="nav-link" exact>Home</router-link>
            <router-link v-if="user" to="/dashboard" class="nav-link"
              >Dashboard</router-link
            >
          </div>

          <div v-if="user" class="user-menu">
            <div class="user-info" @click="toggleDropdown">
              <img
                :src="
                  user.avatarUrl ||
                  'https://ui-avatars.com/api/?name=' +
                    encodeURIComponent(user.name)
                "
                :alt="user.name"
                class="avatar"
              />
              <span class="user-name">{{ user.name }}</span>
            </div>
            <div
              class="dropdown-menu"
              :class="{ 'dropdown-menu-active': dropdownOpen }"
            >
              <router-link
                to="/manage-subscription"
                class="dropdown-item dropdown-manage-sub"
                @click="toggleDropdown"
              >
                Manage Subscription
              </router-link>
              <button class="dropdown-item" @click="logout">Logout</button>
            </div>
          </div>

          <a
            v-else
            :href="getGoogleAuthUrl()"
            class="btn btn-primary nav-sign-in"
            >Sign In</a
          >
        </nav>

        <!-- Loading placeholder -->
        <div v-else class="loader-inline"></div>
      </div>
    </header>

    <!-- Main content area -->
    <main class="main-content">
      <router-view @login-success="checkAuth" />
    </main>

    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <div class="footer-content">
          <div class="copyright">
            <!-- Generated by GitHub Copilot -->
            &copy; {{ new Date().getFullYear() }} ChoreSprint. All rights
            reserved.
          </div>
          <div class="footer-links">
            <a href="#" class="footer-link">Terms</a>
            <a href="#" class="footer-link">Privacy</a>
            <a href="#" class="footer-link">Help</a>
          </div>
        </div>
      </div>
    </footer>
  </div>
</template>

<style>
/* Import main styles */
@import "./styles/main.css";

/* App-specific styles */
.app-container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.main-content {
  flex: 1;
  padding: var(--spacing-xl) 0;
}

.nav-brand-link {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  text-decoration: none;
  color: var(--primary);
  font-weight: 600;
}

.brand-icon {
  font-size: 1.5rem;
}

.nav-links {
  display: flex;
  align-items: center;
  gap: var(--spacing-lg);
}

.nav-links-container {
  display: flex;
  align-items: center;
  gap: var(--spacing-lg);
}

.nav-sign-in {
  margin-left: var(--spacing-md);
}

.user-menu {
  position: relative;
  cursor: pointer;
}

.user-info {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  padding: var(--spacing-xs) var(--spacing-sm);
  border-radius: var(--radius-md);
  transition: background-color var(--transition-fast);
}

.user-info:hover {
  background-color: var(--light);
}

.user-name {
  color: var(--dark);
  font-weight: 500;
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  right: 0;
  width: 150px;
  background-color: var(--white);
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-lg);
  padding: var(--spacing-xs);
  margin-top: var(--spacing-sm);
  z-index: 10;
  display: none;
  opacity: 0;
  transform: translateY(-10px);
  transition:
    opacity 0.2s,
    transform 0.2s;
}

.dropdown-menu-active {
  display: block;
  opacity: 1;
  transform: translateY(0);
}

.dropdown-item {
  display: block;
  width: 100%;
  text-align: left;
  padding: var(--spacing-sm) var(--spacing-md);
  border: none;
  background: none;
  cursor: pointer;
  border-radius: var(--radius-sm);
  transition: background-color var(--transition-fast);
  color: var(--gray-dark);
  text-decoration: none;
}

.dropdown-manage-sub {
  font-size: var(--font-size-sm);
}

.dropdown-item:hover {
  background-color: var(--light);
  color: var(--primary);
}

.footer {
  background-color: var(--white);
  padding: var(--spacing-lg) 0;
  border-top: 1px solid var(--light);
  margin-top: var(--spacing-2xl);
}

.footer-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.copyright {
  color: var(--gray);
  font-size: var(--font-size-sm);
}

.footer-links {
  display: flex;
  gap: var(--spacing-lg);
}

.footer-link {
  color: var(--gray);
  font-size: var(--font-size-sm);
  transition: color var(--transition-fast);
}

.footer-link:hover {
  color: var(--primary);
}

@media (max-width: 768px) {
  .footer-content {
    flex-direction: column;
    gap: var(--spacing-md);
  }
}

.sub-required {
  margin-bottom: var(--spacing-lg);
  padding: var(--spacing-md);
  background-color: var(--warning);
  border: 1px solid var(--warning);
  border-radius: var(--radius-sm);
  text-align: center;
}
</style>
