<script setup lang="ts">
// Generated by GitHub Copilot
import { onMounted, ref, watch } from "vue";
import { useRouter } from "vue-router";
import { getGoogleAuthUrl } from "./utils/config";
import { getAuthStatus } from "./lib/auth";
import { useUserStore } from "./stores/user";

interface User {
  id: string;
  name: string;
  email: string;
  avatarUrl?: string;
}

// State
const user = ref<User | null>(null);
const isLoading = ref(true);
const dropdownOpen = ref(false);
const mobileNavOpen = ref(false);
const subscriptionRequired = ref(false);

// Get router
const router = useRouter();
const userStore = useUserStore();

// Keep local user in sync with the user store
watch(
  () => userStore.user,
  (val) => {
    user.value = val as any;
  },
  { immediate: true }
);

// Toggle dropdown menu
const toggleDropdown = () => {
  dropdownOpen.value = !dropdownOpen.value;
};

// Toggle mobile nav
const toggleMobileNav = () => {
  mobileNavOpen.value = !mobileNavOpen.value;
  // Close dropdown if mobile nav closes
  if (!mobileNavOpen.value) dropdownOpen.value = false;
};

// Close dropdown when clicking outside
const closeDropdownOnClickOutside = (event: MouseEvent) => {
  const userMenu = document.querySelector(".user-menu");
  if (
    userMenu &&
    !userMenu.contains(event.target as Node) &&
    dropdownOpen.value
  ) {
    dropdownOpen.value = false;
  }
};

// Add event listener to close dropdown on clicks outside the menu
onMounted(() => {
  document.addEventListener("click", closeDropdownOnClickOutside);
});

// Close mobile nav on route change
watch(
  () => router.currentRoute.value.fullPath,
  () => {
    mobileNavOpen.value = false;
    dropdownOpen.value = false;
  }
);

// Check if user is logged in
const checkAuth = async () => {
  try {
    const status = await getAuthStatus();
    if (status.authed && !status.subscriptionRequired) {
      user.value = status.user;
      userStore.user = status.user;
      userStore.isAuthenticated = true;
    } else if (status.subscriptionRequired) {
      user.value = status.user;
      userStore.user = status.user;
      userStore.isAuthenticated = true;
      subscriptionRequired.value = true;
      if (router.currentRoute.value.path !== "/manage-account") {
        router.push("/subscribe");
      }
    } else {
      user.value = null;
      userStore.clearUser();
    }
  } catch (error) {
    console.error("Authentication check failed:", error);
    user.value = null;
  } finally {
    isLoading.value = false;
  }
};

// Handle logout
const logout = async () => {
  try {
    await userStore.logout();

    // Clear local state
    user.value = null;

    // Navigate to home page - the stores will handle clearing their state
    router.push("/");
  } catch (error) {
    console.error("Logout failed:", error);
  }
};

// Check auth status on component mount
onMounted(() => {
  checkAuth();
});
</script>

<template>
  <div class="app-container">
    <!-- Navigation bar -->
    <header class="navbar">
      <div class="container nav-container">
        <div class="nav-brand">
          <router-link to="/" class="nav-brand-link">
            <span class="brand-icon">🏃</span> ChoreSprint
          </router-link>
        </div>

        <!-- Hamburger for mobile -->
        <button
          class="mobile-nav-toggle"
          @click="toggleMobileNav"
          aria-label="Toggle navigation"
        >
          <span class="hamburger" :class="{ open: mobileNavOpen }">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
          </span>
        </button>

        <nav
          class="nav-links"
          :class="{
            'nav-links-mobile': true,
            'nav-links-mobile-open': mobileNavOpen,
          }"
          v-if="!isLoading"
        >
          <div class="nav-links-container">
            <router-link to="/" class="nav-link" exact>Home</router-link>
            <router-link v-if="user" to="/dashboard" class="nav-link"
              >Dashboard</router-link
            >
          </div>

          <div v-if="user" class="user-menu">
            <div class="user-info" @click="toggleDropdown">
              <img
                :src="
                  user.avatarUrl ||
                  'https://ui-avatars.com/api/?name=' +
                    encodeURIComponent(user.name)
                "
                :alt="user.name"
                class="avatar"
              />
              <span class="user-name">{{ user.name }}</span>
            </div>
            <div
              class="dropdown-menu"
              :class="{ 'dropdown-menu-active': dropdownOpen }"
            >
              <router-link
                to="/manage-account"
                class="dropdown-item"
                @click="toggleDropdown"
              >
                Manage Account
              </router-link>
              <button class="dropdown-item" @click="logout">Logout</button>
            </div>
          </div>

          <a
            v-else
            :href="getGoogleAuthUrl()"
            class="btn btn-primary nav-sign-in"
            >Sign In</a
          >
        </nav>

        <!-- Loading placeholder -->
        <div v-else class="loader-inline"></div>
      </div>
    </header>

    <!-- Main content area -->
    <main class="main-content">
      <router-view @login-success="checkAuth" />
    </main>

    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <div class="footer-content">
          <div class="copyright">
            <!-- Generated by GitHub Copilot -->
            &copy; {{ new Date().getFullYear() }} ChoreSprint. All rights
            reserved.
          </div>
          <div class="footer-links">
            <a href="#" class="footer-link">Credits</a>
          </div>
        </div>
      </div>
    </footer>
  </div>
</template>

<style>
/* Import main styles */
@import "./styles/main.css";

/* App-specific styles */
.app-container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.main-content {
  flex: 1;
  padding: var(--spacing-xl) 0;
}

.nav-brand-link {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  text-decoration: none;
  color: var(--primary);
  font-weight: 600;
}

.brand-icon {
  font-size: 1.5rem;
}

.nav-links {
  display: flex;
  align-items: center;
  gap: var(--spacing-lg);
}

.nav-links-container {
  display: flex;
  align-items: center;
  gap: var(--spacing-lg);
}

.nav-sign-in {
  margin-left: var(--spacing-md);
}

.user-menu {
  position: relative;
  cursor: pointer;
}

.user-info {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  padding: var(--spacing-xs) var(--spacing-sm);
  border-radius: var(--radius-md);
  transition: background-color var(--transition-fast);
}

.user-info:hover {
  background-color: var(--light);
}

.user-name {
  color: var(--dark);
  font-weight: 500;
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  right: 0;
  width: 150px;
  background-color: var(--white);
  border-radius: var(--radius-md);
  box-shadow: var(--shadow-lg);
  padding: var(--spacing-xs);
  margin-top: var(--spacing-sm);
  z-index: 10;
  display: none;
  opacity: 0;
  transform: translateY(-10px);
  transition:
    opacity 0.2s,
    transform 0.2s;
}

.dropdown-menu-active {
  display: block;
  opacity: 1;
  transform: translateY(0);
}

.dropdown-item {
  display: block;
  width: 100%;
  text-align: left;
  padding: var(--spacing-sm) var(--spacing-md);
  border: none;
  background: none;
  cursor: pointer;
  border-radius: var(--radius-sm);
  transition: background-color var(--transition-fast);
  color: var(--gray-dark);
  text-decoration: none;
  font-size: var(--font-size-sm) !important;
  line-height: 1.5;
}

.dropdown-item:hover {
  background-color: var(--light);
  color: var(--primary);
}

.footer {
  background-color: var(--white);
  padding: var(--spacing-lg) 0;
  border-top: 1px solid var(--light);
  margin-top: var(--spacing-2xl);
}

.footer-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.copyright {
  color: var(--gray);
  font-size: var(--font-size-sm);
}

.footer-links {
  display: flex;
  gap: var(--spacing-lg);
}

.footer-link {
  color: var(--gray);
  font-size: var(--font-size-sm);
  transition: color var(--transition-fast);
}

.footer-link:hover {
  color: var(--primary);
}

/* --- Mobile Styles --- */
@media (max-width: 900px) {
  .nav-container {
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    padding: 0 var(--spacing-md);
  }
  .nav-links {
    display: flex !important;
  }
  .navbar {
    position: relative;
    z-index: 200;
    background: var(--white);
    box-shadow: var(--shadow-md);
  }
  .mobile-nav-toggle {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 40px;
    height: 40px;
    background: none;
    border: none;
    cursor: pointer;
    z-index: 100;
    margin-left: auto;
    padding: 0;
  }
  .hamburger {
    display: inline-block;
    width: 28px;
    height: 22px;
    position: relative;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  }
  .hamburger .bar {
    display: block;
    position: absolute;
    left: 0;
    width: 100%;
    height: 3px;
    background: var(--primary);
    border-radius: 2px;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  }
  .hamburger .bar:nth-child(1) {
    top: 0;
  }
  .hamburger .bar:nth-child(2) {
    top: 9.5px;
  }
  .hamburger .bar:nth-child(3) {
    top: 19px;
  }
  .hamburger.open .bar:nth-child(1) {
    transform: translateY(9.5px) rotate(45deg);
  }
  .hamburger.open .bar:nth-child(2) {
    opacity: 0;
  }
  .hamburger.open .bar:nth-child(3) {
    transform: translateY(-9.5px) rotate(-45deg);
  }
  .nav-links-mobile {
    display: flex;
    flex-direction: column;
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    width: 100vw;
    background: var(--white);
    box-shadow: var(--shadow-lg);
    z-index: 99;
    padding: var(--spacing-xl) var(--spacing-lg);
    transition:
      max-height 0.3s cubic-bezier(0.4, 0, 0.2, 1),
      opacity 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    gap: var(--spacing-xl);
    align-items: flex-start;
    justify-content: flex-start;
    max-height: 0;
    opacity: 0;
    overflow: hidden;
    pointer-events: none;
  }
  .nav-links-mobile-open {
    max-height: 500px;
    opacity: 1;
    pointer-events: auto;
    display: flex;
  }
  .nav-links-container {
    flex-direction: column;
    gap: var(--spacing-lg);
    width: 100%;
  }
  .user-menu {
    width: 100%;
    margin-top: var(--spacing-lg);
  }
  .dropdown-menu {
    position: static;
    box-shadow: none;
    margin-top: 0;
    width: 100%;
    border-radius: var(--radius-md);
    background: var(--light);
    opacity: 1;
    display: none;
    transform: none;
    transition: none;
  }
  .dropdown-menu-active {
    display: block;
  }
  .dropdown-item {
    width: 100%;
    padding: var(--spacing-sm) var(--spacing-md);
    font-size: var(--font-size-sm) !important;
    line-height: 1.5;
  }
  .nav-sign-in {
    width: 100%;
    margin: var(--spacing-md) 0 0 0;
    text-align: left;
  }
  .main-content {
    padding: var(--spacing-md) 0;
  }
  .footer-content {
    flex-direction: column;
    gap: var(--spacing-md);
    align-items: flex-start;
  }
  .footer {
    padding: var(--spacing-md) 0;
    margin-top: var(--spacing-lg);
  }
}

@media (max-width: 500px) {
  .nav-brand-link {
    font-size: 1.1rem;
  }
  .brand-icon {
    font-size: 1.1rem;
  }
  .main-content {
    padding: var(--spacing-sm) 0;
  }
  .footer {
    padding: var(--spacing-sm) 0;
  }
}

.sub-required {
  margin-bottom: var(--spacing-lg);
  padding: var(--spacing-md);
  background-color: var(--warning);
  border: 1px solid var(--warning);
  border-radius: var(--radius-sm);
  text-align: center;
}
</style>
