// src/main.ts
// Generated by GitHub Copilot
import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";

// Import global styles
import "./styles/main.css";

// Create and configure app
const app = createApp(App);
const pinia = createPinia();

// Use plugins
app.use(router);
app.use(pinia);

// Mount the app
app.mount("#app");
